import { Dish, DishCategory } from "./types";

// 默认菜品图片（Base64编码的占位图）
const createPlaceholderImage = (name: string, category: string) => {
  const colorMap: Record<string, string> = {
    special: '#DC2626',
    jianghu: '#F59E0B',
    vegetable: '#22C55E',
    soup: '#EAB308',
    alcohol: '#8B5CF6',
    beverage: '#3B82F6'
  };
  const color = colorMap[category] || '#6B7280';
  const firstChar = name.charAt(0);

  // 创建SVG占位图并转换为Base64
  const svg = `
    <svg width="300" height="200" xmlns="http://www.w3.org/2000/svg">
      <rect width="300" height="200" fill="${color}" opacity="0.2"/>
      <rect width="300" height="200" fill="${color}"/>
      <text x="150" y="100" font-family="Arial, sans-serif" font-size="60" fill="white" text-anchor="middle" font-weight="bold" dominant-baseline="middle">${firstChar}</text>
      <text x="150" y="140" font-family="Arial, sans-serif" font-size="16" fill="white" text-anchor="middle">${name}</text>
    </svg>
  `;

  return `data:image/svg+xml;base64,${btoa(unescape(encodeURIComponent(svg)))}`;
};

// 菜品数据 - 本地图片（Base64）
export const sampleDishes: Dish[] = [
  // ============ 汤类 (soup) - 8道 ============
  {
    id: "s1",
    name: "滑肉汤",
    category: "soup",
    price: 38,
    image: createPlaceholderImage("滑肉汤", "soup"),
    isAvailable: true,
  },
  {
    id: "s2",
    name: "酥肉汤",
    category: "soup",
    price: 28,
    image: createPlaceholderImage("酥肉汤", "soup"),
    isAvailable: true,
  },
  {
    id: "s3",
    name: "番茄丸子汤",
    category: "soup",
    price: 28,
    image: createPlaceholderImage("番茄丸子汤", "soup"),
    isAvailable: true,
  },
  {
    id: "s4",
    name: "三鲜汤",
    category: "soup",
    price: 28,
    image: createPlaceholderImage("三鲜汤", "soup"),
    isAvailable: true,
  },
  {
    id: "s5",
    name: "黄瓜皮蛋汤",
    category: "soup",
    price: 15,
    image: createPlaceholderImage("黄瓜皮蛋汤", "soup"),
    isAvailable: true,
  },
  {
    id: "s6",
    name: "酸菜粉丝汤",
    category: "soup",
    price: 15,
    image: createPlaceholderImage("酸菜粉丝汤", "soup"),
    isAvailable: true,
  },
  {
    id: "s7",
    name: "小菜豆腐汤",
    category: "soup",
    price: 15,
    image: createPlaceholderImage("小菜豆腐汤", "soup"),
    isAvailable: true,
  },
  {
    id: "s8",
    name: "蕃茄鸡蛋汤",
    category: "soup",
    price: 15,
    image: createPlaceholderImage("蕃茄鸡蛋汤", "soup"),
    isAvailable: true,
  },

  // ============ 素菜 (vegetable) - 12道 ============
  {
    id: "v1",
    name: "木耳山药",
    category: "vegetable",
    price: 20,
    image: createPlaceholderImage("木耳山药", "vegetable"),
    isAvailable: true,
  },
  {
    id: "v2",
    name: "苦瓜蛋饼",
    category: "vegetable",
    price: 20,
    image: createPlaceholderImage("苦瓜蛋饼", "vegetable"),
    isAvailable: true,
  },
  {
    id: "v3",
    name: "干煸四季豆",
    category: "vegetable",
    price: 18,
    image: createPlaceholderImage("干煸四季豆", "vegetable"),
    isAvailable: true,
  },
  {
    id: "v4",
    name: "蚂蚁上树",
    category: "vegetable",
    price: 18,
    image: createPlaceholderImage("蚂蚁上树", "vegetable"),
    isAvailable: true,
  },
  {
    id: "v5",
    name: "油渣莲白",
    category: "vegetable",
    price: 18,
    image: createPlaceholderImage("油渣莲白", "vegetable"),
    isAvailable: true,
  },
  {
    id: "v6",
    name: "豇豆茄子",
    category: "vegetable",
    price: 18,
    image: createPlaceholderImage("豇豆茄子", "vegetable"),
    isAvailable: true,
  },
  {
    id: "v7",
    name: "蕃茄炒蛋",
    category: "vegetable",
    price: 18,
    image: createPlaceholderImage("蕃茄炒蛋", "vegetable"),
    isAvailable: true,
  },
  {
    id: "v8",
    name: "麻婆豆腐",
    category: "vegetable",
    price: 18,
    image: createPlaceholderImage("麻婆豆腐", "vegetable"),
    isAvailable: true,
  },
  {
    id: "v9",
    name: "韭菜炒豆干",
    category: "vegetable",
    price: 18,
    image: createPlaceholderImage("韭菜炒豆干", "vegetable"),
    isAvailable: true,
  },
  {
    id: "v10",
    name: "泡椒血旺",
    category: "vegetable",
    price: 15,
    image: createPlaceholderImage("泡椒血旺", "vegetable"),
    isAvailable: true,
  },
  {
    id: "v11",
    name: "时蔬",
    category: "vegetable",
    price: 15,
    image: createPlaceholderImage("时蔬", "vegetable"),
    isAvailable: true,
  },
  {
    id: "v12",
    name: "青椒土豆丝",
    category: "vegetable",
    price: 15,
    image: createPlaceholderImage("青椒土豆丝", "vegetable"),
    isAvailable: true,
  },

  // ============ 江湖菜 (jianghu) - 29道 ============
  {
    id: "j1",
    name: "泡椒羊肉",
    category: "jianghu",
    price: 68,
    image: createPlaceholderImage("泡椒羊肉", "jianghu"),
    isAvailable: true,
  },
  {
    id: "j2",
    name: "蒜香排骨",
    category: "jianghu",
    price: 78,
    image: createPlaceholderImage("蒜香排骨", "jianghu"),
    isAvailable: true,
  },
  {
    id: "j3",
    name: "香辣手抓排骨",
    category: "jianghu",
    price: 78,
    image: createPlaceholderImage("香辣手抓排骨", "jianghu"),
    isAvailable: true,
  },
  {
    id: "j4",
    name: "粉蒸羊肉",
    category: "jianghu",
    price: 68,
    image: createPlaceholderImage("粉蒸羊肉", "jianghu"),
    isAvailable: true,
  },
  {
    id: "j5",
    name: "麻辣香酥蛙",
    category: "jianghu",
    price: 58,
    image: createPlaceholderImage("麻辣香酥蛙", "jianghu"),
    isAvailable: true,
  },
  {
    id: "j6",
    name: "生煎肥肠",
    category: "jianghu",
    price: 58,
    image: createPlaceholderImage("生煎肥肠", "jianghu"),
    isAvailable: true,
  },
  {
    id: "j7",
    name: "尖椒美蛙的诱惑",
    category: "jianghu",
    price: 58,
    image: createPlaceholderImage("尖椒美蛙的诱惑", "jianghu"),
    isAvailable: true,
  },
  {
    id: "j8",
    name: "水煮牛肉",
    category: "jianghu",
    price: 58,
    image: createPlaceholderImage("水煮牛肉", "jianghu"),
    isAvailable: true,
  },
  {
    id: "j9",
    name: "红烧肥肠",
    category: "jianghu",
    price: 48,
    image: createPlaceholderImage("红烧肥肠", "jianghu"),
    isAvailable: true,
  },
  {
    id: "j10",
    name: "农家土腊肉",
    category: "jianghu",
    price: 48,
    image: createPlaceholderImage("农家土腊肉", "jianghu"),
    isAvailable: true,
  },
  {
    id: "j11",
    name: "香辣肥肠",
    category: "jianghu",
    price: 48,
    image: createPlaceholderImage("香辣肥肠", "jianghu"),
    isAvailable: true,
  },
  {
    id: "j12",
    name: "小炒黄牛肉",
    category: "jianghu",
    price: 48,
    image: createPlaceholderImage("小炒黄牛肉", "jianghu"),
    isAvailable: true,
  },
  {
    id: "j13",
    name: "泡椒牛肉丝",
    category: "jianghu",
    price: 48,
    image: createPlaceholderImage("泡椒牛肉丝", "jianghu"),
    isAvailable: true,
  },
  {
    id: "j14",
    name: "土豆片炒农家盐肉",
    category: "jianghu",
    price: 48,
    image: createPlaceholderImage("土豆片炒农家盐肉", "jianghu"),
    isAvailable: true,
  },
  {
    id: "j15",
    name: "自串牙签肉",
    category: "jianghu",
    price: 48,
    image: createPlaceholderImage("自串牙签肉", "jianghu"),
    isAvailable: true,
  },
  {
    id: "j16",
    name: "白油肚条",
    category: "jianghu",
    price: 48,
    image: createPlaceholderImage("白油肚条", "jianghu"),
    isAvailable: true,
  },
  {
    id: "j17",
    name: "合川肉片",
    category: "jianghu",
    price: 48,
    image: createPlaceholderImage("合川肉片", "jianghu"),
    isAvailable: true,
  },
  {
    id: "j18",
    name: "腊肉拼盘",
    category: "jianghu",
    price: 48,
    image: createPlaceholderImage("腊肉拼盘", "jianghu"),
    isAvailable: true,
  },
  {
    id: "j19",
    name: "大刀烧白",
    category: "jianghu",
    price: 48,
    image: createPlaceholderImage("大刀烧白", "jianghu"),
    isAvailable: true,
  },
  {
    id: "j20",
    name: "水煮肉片",
    category: "jianghu",
    price: 38,
    image: createPlaceholderImage("水煮肉片", "jianghu"),
    isAvailable: true,
  },
  {
    id: "j21",
    name: "肝腰合炒",
    category: "jianghu",
    price: 38,
    image: createPlaceholderImage("肝腰合炒", "jianghu"),
    isAvailable: true,
  },
  {
    id: "j22",
    name: "回锅肉",
    category: "jianghu",
    price: 28,
    image: createPlaceholderImage("回锅肉", "jianghu"),
    isAvailable: true,
  },
  {
    id: "j23",
    name: "泡椒儿肠",
    category: "jianghu",
    price: 38,
    image: createPlaceholderImage("泡椒儿肠", "jianghu"),
    isAvailable: true,
  },
  {
    id: "j24",
    name: "盐煎肉",
    category: "jianghu",
    price: 28,
    image: createPlaceholderImage("盐煎肉", "jianghu"),
    isAvailable: true,
  },
  {
    id: "j25",
    name: "农家小炒肉",
    category: "jianghu",
    price: 28,
    image: createPlaceholderImage("农家小炒肉", "jianghu"),
    isAvailable: true,
  },
  {
    id: "j26",
    name: "蒜泥白肉",
    category: "jianghu",
    price: 28,
    image: createPlaceholderImage("蒜泥白肉", "jianghu"),
    isAvailable: true,
  },
  {
    id: "j27",
    name: "鱼香肉丝",
    category: "jianghu",
    price: 28,
    image: createPlaceholderImage("鱼香肉丝", "jianghu"),
    isAvailable: true,
  },
  {
    id: "j28",
    name: "雷椒皮蛋",
    category: "jianghu",
    price: 28,
    image: createPlaceholderImage("雷椒皮蛋", "jianghu"),
    isAvailable: true,
  },
  {
    id: "j29",
    name: "红烧羊肉",
    category: "jianghu",
    price: 88,
    image: createPlaceholderImage("红烧羊肉", "jianghu"),
    isAvailable: true,
  },

  // ============ 酒水类 (alcohol) - 6种 ============
  {
    id: "a1",
    name: "江小白",
    category: "alcohol",
    price: 25,
    image: createPlaceholderImage("江小白", "alcohol"),
    isAvailable: true,
  },
  {
    id: "a2",
    name: "江小白（大瓶）",
    category: "alcohol",
    price: 45,
    image: createPlaceholderImage("江小白大瓶", "alcohol"),
    isAvailable: true,
  },
  {
    id: "a3",
    name: "劲酒",
    category: "alcohol",
    price: 20,
    image: createPlaceholderImage("劲酒", "alcohol"),
    isAvailable: true,
  },
  {
    id: "a4",
    name: "劲酒（大瓶）",
    category: "alcohol",
    price: 38,
    image: createPlaceholderImage("劲酒大瓶", "alcohol"),
    isAvailable: true,
  },
  {
    id: "a5",
    name: "雪花勇闯天涯",
    category: "alcohol",
    price: 8,
    image: createPlaceholderImage("雪花勇闯天涯", "alcohol"),
    isAvailable: true,
  },
  {
    id: "a6",
    name: "雪花纯生",
    category: "alcohol",
    price: 10,
    image: createPlaceholderImage("雪花纯生", "alcohol"),
    isAvailable: true,
  },

  // ============ 饮料类 (beverage) - 12种 ============
  {
    id: "b1",
    name: "可口可乐",
    category: "beverage",
    price: 6,
    image: createPlaceholderImage("可口可乐", "beverage"),
    isAvailable: true,
  },
  {
    id: "b2",
    name: "百事可乐",
    category: "beverage",
    price: 6,
    image: createPlaceholderImage("百事可乐", "beverage"),
    isAvailable: true,
  },
  {
    id: "b3",
    name: "雪碧",
    category: "beverage",
    price: 6,
    image: createPlaceholderImage("雪碧", "beverage"),
    isAvailable: true,
  },
  {
    id: "b4",
    name: "芬达",
    category: "beverage",
    price: 6,
    image: createPlaceholderImage("芬达", "beverage"),
    isAvailable: true,
  },
  {
    id: "b5",
    name: "美年达",
    category: "beverage",
    price: 6,
    image: createPlaceholderImage("美年达", "beverage"),
    isAvailable: true,
  },
  {
    id: "b6",
    name: "冰红茶",
    category: "beverage",
    price: 6,
    image: createPlaceholderImage("冰红茶", "beverage"),
    isAvailable: true,
  },
  {
    id: "b7",
    name: "绿茶",
    category: "beverage",
    price: 6,
    image: createPlaceholderImage("绿茶", "beverage"),
    isAvailable: true,
  },
  {
    id: "b8",
    name: "果粒橙",
    category: "beverage",
    price: 8,
    image: createPlaceholderImage("果粒橙", "beverage"),
    isAvailable: true,
  },
  {
    id: "b9",
    name: "鲜橙多",
    category: "beverage",
    price: 8,
    image: createPlaceholderImage("鲜橙多", "beverage"),
    isAvailable: true,
  },
  {
    id: "b10",
    name: "营养快线",
    category: "beverage",
    price: 8,
    image: createPlaceholderImage("营养快线", "beverage"),
    isAvailable: true,
  },
  {
    id: "b11",
    name: "AD钙奶",
    category: "beverage",
    price: 5,
    image: createPlaceholderImage("AD钙奶", "beverage"),
    isAvailable: true,
  },
  {
    id: "b12",
    name: "旺仔牛奶",
    category: "beverage",
    price: 6,
    image: createPlaceholderImage("旺仔牛奶", "beverage"),
    isAvailable: true,
  },
  {
    id: "b13",
    name: "酸梅汤",
    category: "beverage",
    price: 8,
    image: createPlaceholderImage("酸梅汤", "beverage"),
    isAvailable: true,
  },
];

export const DEFAULT_TABLES = Array.from({ length: 20 }, (_, i) => ({
  value: String(i + 1),
  label: `${i + 1}号桌`,
}));

export const DEFAULT_PEOPLE = Array.from({ length: 10 }, (_, i) => ({
  value: String(i),
  label: i === 0 ? "未填写" : `${i}人`,
}));
